#!/bin/sh

export SPRING_DATASOURCE_URL="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
export SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
export SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
export MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health

exec "$@"
